menu/urls.py
from django.urls import path

from menu.views import (
    AddItemView,
    ItemDetailView,
    ItemListView,
    OrderCheckoutView,
    OrderView,
    RemoveItemView,
)

app_name = "menu"

urlpatterns = [
    path("", ItemListView.as_view(), name="all"),
    path("item/<int:pk>", ItemDetailView.as_view(), name="item"),
    path("order/", OrderView.as_view(), name="order"),
    path("add_item/<int:item_id>", AddItemView.as_view(), name="add_item"),
    path(
        "remove_item/<int:item_id>",
        RemoveItemView.as_view(),
        name="remove_item",
    ),
    path("order/checkout", OrderCheckoutView.as_view(), name="order_checkout"),
]

restaurant_menu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
]

urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

menu/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg, F, Sum

from restaurant_menu import settings


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]
        verbose_name_plural = "Categories"


class Allergen(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    calories = models.IntegerField()
    allergens = models.ManyToManyField(Allergen, blank=True)
    image = models.ImageField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.name} - id: {self.id}"

    class Meta:
        ordering = ["category"]

    def get_allergens(self):
        return self.allergens.all()

    def get_image_url(self):
        if self.image:
            return self.image.url

        return "https://placehold.co/600x400.png"

    def get_average_rating(self):
        return self.orderitem_set.aggregate(avg_rating=Avg("rating"))[
            "avg_rating"
        ]


class Chef(models.Model):
    ON_DUTY = "ON DUTY"
    OFF_DUTY = "OFF DUTY"
    CHEF_STATUS_CHOICES = {
        ON_DUTY: "On Duty",
        OFF_DUTY: "Off Duty",
    }

    name = models.CharField(max_length=50)
    status = models.CharField(
        max_length=10, choices=CHEF_STATUS_CHOICES, default=ON_DUTY
    )

    def __str__(self):
        return self.name


class Order(models.Model):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    PROCESSING = "PROCESSING"
    DONE = "DONE"
    CANCELLED = "CANCELLED"

    ORDER_STATUS_CHOICES = {
        PENDING: "Pending",
        ACCEPTED: "Accepted",
        PROCESSING: "Processing",
        DONE: "Done",
        CANCELLED: "Cancelled",
    }
    table = models.ForeignKey(
        "Table", on_delete=models.SET_NULL, null=True, blank=True
    )
    chef = models.ForeignKey(
        Chef, on_delete=models.SET_NULL, null=True, blank=True
    )
    items = models.ManyToManyField(
        Item, through="OrderItem", related_name="orders_items"
    )
    status = models.CharField(
        max_length=15, choices=ORDER_STATUS_CHOICES, default=PENDING
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f"Order # {self.id}"

    def get_order(self, table_id):
        order, _ = (
            Order.objects.select_related("table")
            .prefetch_related("items")
            .get_or_create(table_id=table_id, status="PENDING")
        )

    def get_total_amount(self):
        total = self.orderitem_set.aggregate(
            total_amount=Sum(F("item__price") * F("quantity"))
        )
        return total["total_amount"]

    def get_total_items(self):
        total = self.orderitem_set.aggregate(total_items=Sum("quantity"))
        return total["total_items"]

    def get_order_allergens(self):
        return (
            self.orderitem_set.prefetch_related("item__allergies")
            .values_list("item__allergies__name", flat=True)
            .distinct()
        )

    def get_items(self):
        return self.orderitem_set.prefetch_related("item")

    def add_item(self, item_id):
        orderitem, created = self.orderitem_set.get_or_create(item_id=item_id)
        if created:
            return

        orderitem.quantity = F("quantity") + 1
        orderitem.save()

    def remove_item(self, item_id):
        orderitem = self.orderitem_set.get(item_id=item_id)
        orderitem.quantity = F("quantity") - 1
        orderitem.save()

        if self.orderitem_set.get(item_id=item_id).quantity == 0:
            orderitem.delete()


class Table(models.Model):
    """
    Table Model, by default the number of tables is 13.
    You may change the number of tables manually
    """

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    TABLE_STATUS_CHOICES = {
        OPEN: "Open",
        CLOSED: "Closed",
    }

    def get_table_numbers():
        table_choices = []
        for x in range(1, settings.NUMBER_OF_TABLES + 1):
            table_choices.append((f"{x}", f"Table #{x}"))
        return table_choices

    number = models.CharField(max_length=10, choices=get_table_numbers())
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.CharField(max_length=10, choices=TABLE_STATUS_CHOICES)

    def __str__(self):
        return f"Table {self.number}, user: {self.user}, status: {self.status}"

    def get_order(self):
        order, _ = Order.objects.get_or_create(table_id=self.id)

        return order


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(
        Item, on_delete=models.SET_NULL, null=True, blank=True
    )
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f"Order {self.order_id} Item {self.item} x {self.quantity} pcs."

    def get_total_amount(self):
        return self.item.price * self.quantity

    class Meta:
        unique_together = ("order", "item")

    constraints = [
        models.CheckConstraint(
            check=models.Q(rating__lte=5), name="rating__lte_5"
        ),
        models.CheckConstraint(
            check=models.Q(rating__gte=1), name="rating__gte_1"
        ),
    ]

menu/views.py
import re

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView

from menu.models import Chef, Item, Order, OrderItem, Table


# Create your views here.
class ItemListView(View):
    template_name = "menu/item_list.html"

    def get(self, request, *args, **kwargs):
        _search = request.GET.get("search")
        if _search is not None and _search.strip():
            query = Q(name__icontains=_search) | Q(
                description__icontains=_search
            )

            items = (
                Item.objects.filter(query)
                .select_related("category")
                .order_by("category")
            )

        else:
            items = (
                Item.objects.all()
                .select_related("category")
                .order_by("category")
            )
        ctx = {"item_list": items, "search": _search}

        return render(
            request, template_name="menu/item_list.html", context=ctx
        )


class ItemDetailView(DetailView):
    model = Item


class OrderView(LoginRequiredMixin, ListView):
    model = Order

    def get(self, request, *args, **kwargs):
        if not hasattr(request.user, "table"):
            return render(request, "menu/no_table.html")

        order = (
            Table.objects.select_related("orders")
            .get(id=request.user.table.id)
            .get_order()
        )

        orderitem_list = order.get_items()

        ctx = {"order": order, "orderitem_list": orderitem_list}
        return render(
            request,
            "menu/order.html",
            ctx,
        )


class AddItemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(
            request.META.get("HTTP_REFERER", reverse_lazy("menu:order"))
        )

    def post(self, request, item_id):
        order = Table.objects.get(id=request.user.table.id).get_order()
        order.add_item(item_id)

        return HttpResponseRedirect(
            request.META.get("HTTP_REFERER", reverse_lazy("menu:order"))
        )


class RemoveItemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(
            request.META.get("HTTP_REFERER", reverse_lazy("menu:order"))
        )

    def post(self, request, item_id):
        order = Table.objects.get(id=request.user.table.id).get_order()
        order.remove_item(item_id)

        return HttpResponseRedirect(
            request.META.get("HTTP_REFERER", reverse_lazy("menu:order"))
        )


class OrderCheckoutView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        table = Table.objects.get(user_id=request.user.id)
        order = Order.objects.get(table_id=table.id, status="P")
        order.status = "A"
        order.modified_at = timezone.now()
        order.save()

        return HttpResponseRedirect("/")

menu/templates/menu/base.html
{% load crispy_forms_tags %}
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>at Ilerio Def's</title>
    <link href="https://bootswatch.com/5/united/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="">
    {#    NAVBAR START#}
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url "menu:all" %}">At Ilerio Def's</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url "menu:all" %}">Menu
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "menu:order" %}">Order</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "login" %}">Login</a>
                    </li>

                </ul>
                <form class="d-flex" action="{% url "menu:all" %}">
                    <label>
                        <input class="form-control me-sm-2" type="text" placeholder="Search..." name="search"
                                {% if search %} value="{{ search }}" {% endif %}
                        >
                    </label>
                    <button class="btn btn-secondary my-2 my-sm-0 mx-2" type="submit">Search</button>
                    <button type="button" class="btn btn btn-outline-primary"><a href="{% url 'menu:all' %}">Reset</a></button>
                </form>
            </div>
        </div>
    </nav>
    {#    NAVBAR END#}
</div>
<div class="container align-content-center">
    {% block content %}

    {% endblock %}
</div>

<!-- component -->


<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2024 Ilerio Def</p>
</footer>

</body>
</html>

menu/templates/menu/item_detail.html
{% extends "menu/base.html" %}
{% load static %}


{% block content %}

    <h1>{{ item.name }}</h1>
    <h2>{{ item.description }}</h2>
    <div class="">
        <img class="img-fluid" src="{{ item.get_image_url }}">
    </div>
    {% with allergens=item.allergens.all %}
        {% if allergens %}
            <div class="">this item contains the following allergens: {{ allergens|join:", " }}</div>
        {% endif %}
    {% endwith %}
    <div class="">Calories per item: {{ item.calories }} Ccal.</div>
    <div>Price: ${{ item.price }}</div>
{% endblock %}

menu/templates/menu/item_list.html
{% extends "menu/base.html" %}
{% load static %}




{% block content %}
    <div class="p-3 row row-cols-3">
        {% for item in item_list %}
            <div class="col-3 offset-1 container border-2">
                <div class="card border-secondary mb-3" style="max-width: 20rem;">
                    <div class="card-header text-uppercase">{{ item.category }}</div>
                    <div class="card-body">
                        <div class="h-50" >
                            <img src='{{ item.get_image_url }}' class="img-thumbnail card-img-top rounded-3 bg-body-secondary">
                        </div>
                        <h4 class="card-title">
                            <a class ="link-opacity-50-hover icon-link" href="{% url "menu:item" pk=item.id %}">{{ item.name }}</a>
                        </h4>
                        <p class="card-text">{{ item.description }}.</p>
                    </div>
                    <div class="card-footer">
                        <div class="container row align-content-center">
                            <div class="col text-end">$ {{ item.price }}</div>
                            {% with rating=item.get_average_rating %}
                                {% if rating %}
                            <div class="col-form-label">Rating: {{ rating }}</div>
                                    {% else %}
                            <div class="col-form-label">Be first to rate!</div>

                            {% endif %}
                            {% endwith %}
                            <div class="col text-end">
                                <form action="{% url 'menu:add_item' item.id %}" method="post">
                                    {% csrf_token %}
                                    {{form}}
                                    <button type="button submit" class="btn btn-outline-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket" viewBox="0 0 16 16">
                                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9zM1 7v1h14V7zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5"/>
                                        </svg>
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>


        {% endfor %}
    </div>
{% endblock %}

menu/templates/menu/no_table.html
{% extends "menu/base.html" %}
{% load static %}
{% block content %}
<h1>An error occured</h1>
    <h2>We're terribly sorry, but there is no table associated with this account. Please contact the administrator for account modifications</h2>
{% endblock  %}

menu/templates/menu/order.html
{% extends "menu/base.html" %}
{% load static %}
{% block content %}
    <div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-lg-12">
            <div class="box-element">

                <a  class="btn btn-outline-dark mt-1" href="{% url 'menu:all' %}">&#x2190; Back to menu</a>
                <br>
                <br>
                <table aria-describedby="table-order-total" class="table">
                    <tr>
                        <caption id="table-order-total">Order Total</caption>
                    </tr>
                    <tr>
                    {% with order_total=order.get_total_amount %}
                        {% if order_total %}
                            <th><h5>Items: <strong>{{order.get_total_items }} item(s)</strong></h5></th>
                            <br>
                            <th><h5>Total:<strong> ${{order_total|floatformat:2}}</strong></h5></th>
                        {% else %}<th><h5>There are no items in your order</h5></th>
                        <th>logged as: {{ user }}</th>

                        <th>
                            <br>
                                <form action="{% url 'menu:order_checkout' %}" method="post">
                                    {% csrf_token %}
                                    {{ form }}
                                    <button type="button submit" class="btn btn-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293z"/>
                                        </svg>
                                    </button>
                                </form>
                            {% endif %}
                    {% endwith %}

                        </th>
                        <th>
                            <br>
                        {% with allergens=order.get_allergens %}
                            {% if allergens %}
                                <div class="alert alert-dismissible alert-warning">
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                    <div class="card">
                                        <h5 class="">Please be advised that your order contains following allergens:</h5>
                                        <h5 class="mb-0 flex text-uppercase w-auto">
                                            <strong>
                                                {{ allergens|join:", " }}
                                            </strong>
                                        </h5>
                                    </div>
                                </div>
                            {% endif %}
                        {% endwith %}
                        </th>
                    </tr>
                </table>

            </div>


            <div class="row-cols-auto">
                <div class="row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>

                {% for item in orderitem_list %}
                    <div class="row">
                        <div style="flex:2"><img class="img-thumbnail card-img-top rounded-3 bg-body-secondary" src="{{item.item.get_image_url}}" alt="{{ item.product.name }}"></div>
                        <div style="flex:2"><p>{{item.item.name}}</p></div>
                        <div style="flex:1"><p>${{item.item.price}}</p></div>
                        <div style="flex:1" class="inline">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <form action="{% url 'menu:remove_item' item.item.id %}" method="post">
                                    {% csrf_token %}
                                    {{ form }}

                                    <button type="button submit" class="btn btn-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293z"/>
                                        </svg>
                                    </button>
                                </form>

                                <button type="button" class="btn btn-secondary" disabled>{{ item.quantity }}</button>
                                <form action="{% url 'menu:add_item' item.item.id %}" method="post">
                                    {% csrf_token %}
                                    {{ form }}

                                    <button type="button submit" class="btn btn-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707z"/>
                                        </svg>
                                    </button>
                                </form>

                            </div>

                        </div>
                        <div style="flex:1"><p>$ {{item.get_total_amount }}</p></div>
                    </div>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
{% endblock content %}